version: '3'
services:
    elastic:
        image: elasticsearch:7.12.0
        ports:
            - "9000:9000"
            - "9200:9200"
            - "9300:9300"
        environment: 
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    kibana:
        image: docker.elastic.co/kibana/kibana:7.12.1
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_HOSTS: "http://elastic:9200"
        depends_on:
            - elastic
        ports:
            - "5601:5601"
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
        - '2181:2181'
        environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    kafdrop:
        image: 'obsidiandynamics/kafdrop:3.27.0'
        ports:
            - '9090:9000'
        environment:
            - KAFKA_BROKERCONNECT="kafka:9092"
            - SERVER_SERVLET_CONTEXTPATH="/"
        depends_on:
            - kafka
    postgres:
        image: postgres
        volumes:
          - ./fixtures/footballclub.sql:/docker-entrypoint-initdb.d/footballclub.sql
        ports: 
            - "5432:5432"
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
        - "5050:80"
        depends_on:
            - postgres
