CREATE TABLE footballclub (
    id serial PRIMARY KEY,
    name text not null,
	tournaments text[] not null,
	nation text not null,
	hasstadium boolean not null,
    description text not null,
	rating float
);

INSERT INTO footballclub (name, tournaments, nation, hasstadium, description, rating) VALUES
	('FC Barcelona', array['Laliga', 'Uefa Champions League', 'Copa Del Rey', 'Spanish Supercup'], 'Spanyol', TRUE, 'Fútbol Club Barcelona, juga dikenal sebagai Barcelona atau Barça, adalah klub sepak bola profesional yang berbasis di Barcelona, Catalunya, Spanyol. Didirikan pada tahun 1899 oleh sekelompok pemain Swiss, Inggris, Jerman dan Katalan yang dipimpin oleh Joan Gamper, klub telah menjadi simbol budaya Catalan dan Catalanisme, yang mempunyai motto "Més que un club" (Lebih dari sebuah klub).', 5),
	('Arsenal FC', array['English Premier League', 'Uefa Europa League', 'FA Cup'], 'Inggris', TRUE, 'Arsenal Football Club (dikenal pula sebagai Arsenal atau The Gunners) adalah klub sepak bola profesional Inggris yang berbasis di daerah Holloway, London. Didirikan pada 1886 dengan nama Dial Square. Klub ini bermain di Liga Utama Inggris yang termasuk salah satu klub tersukses di sepak bola Inggris, yang telah memenangkan 13 gelar kasta utama Liga Inggris (10 pada era Divisi Pertama dan 3 pada era Premier League) dan 14 gelar di Piala FA (Gelar paling banyak). Arsenal memegang rekor untuk periode terpanjang berada di kasta puncak Liga Inggris tanpa pernah terdegradasi sejak musim 1919 dan menjadi tim pada peringkat pertama dalam klasemen Liga Inggris sepanjang abad ke-20.[3] Arsenal menjadi tim kedua di Inggris yang menyelesaikan semusim liga tanpa kalah (musim 2003–04) dan tim pertama yang melakukannya pada era di mana satu musim berlangsung 38 pertandingan.', 4.5),																		
	('Chelsea FC', array['English Premier League','Uefa Europa League', 'FA Cup'], 'Inggris', TRUE, 'Chelsea Football Club adalah sebuah klub sepak bola yang bermarkas di Fulham, London. Chelsea didirikan pada tahun 1905 dan kini berkompetisi di Liga Utama Inggris.', 5),
	('Real Madrid', array['Laliga', 'Uefa Champions League', 'Copa Del Rey', 'Spanish Supercup'], 'Spanyol', TRUE, 'Real Madrid Club de Fútbol, Royal Madrid Football Club), umumnya dikenal sebagai Real Madrid, adalah klub sepak bola profesional yang berbasis di Madrid, Spanyol.', 5),
	('Wolverhampton', array['English Premier League','Uefa Europa League', 'FA Cup'], 'Inggris', FALSE, 'Wolverhampton Wanderers Football Club adalah sebuah klub sepak bola Inggris yang bermarkas di Wolverhampton, Britania Raya yang bermain di Liga Utama Inggris. Klub ini memainkan pertandingan kandangnya di Stadion Molineux yang berkapasitas 32,050 penonton. Seragam mereka berwarna cokelat-hitam. Mereka dijuluki Wolves.', 3.8),																								
	('Tottenham Hotspur', array['English Premier League', 'UEFA Conference League', 'FA Cup'], 'Inggris', FALSE, 'Tottenham Hotspur Football Club adalah klub sepak bola yang berasal dari Tottenham, sebuah daerah yang berada di wilayah utara London. Mereka juga dikenal sebagai Spurs, The Spurs dan Tottenham, sementara penggemar mereka memberi mereka nama the Lilywhites karena seragam tradisional mereka yang berwarna putih.',3.9),																						
	('Persija Jakarta', array['Liga 1'], 'Indonesia', FALSE, 'Persija singkatan dari Persatuan Sepak Bola Indonesia Jakarta (dahulu dikenal juga dengan nama Persija Pusat) adalah klub sepak bola Indonesia yang berbasis di Jakarta. Persija saat ini berlaga di Liga 1. Persija merupakan salah satu klub sepakbola paling sukses di sejarah sepakbola Indonesia dengan torehan 2 kali juara liga domestik dan 9 kali juara turnamen perserikatan hingga sejauh ini.', 2.8),																									
	('Leicester City', array['English Premier League', 'FA Cup', 'Uefa Europa League'], 'Inggris', TRUE, 'Leicester City Football Club adalah klub sepak bola profesional yang berbasis di Leicester di East Midlands, Inggris. Klub bersaing di Liga Premier, tingkat atas sistem liga sepak bola Inggris, dan memainkan pertandingan kandangnya di Stadion King Power.', 4),	
	('Persib Bandung', array['Liga 1'], 'Indonesia', FALSE, 'Persib (atau singkatan dari Persatuan Sepak Bola Indonesia Bandung) adalah klub sepak bola Indonesia yang berdiri pada 14 Maret 1933, berbasis di Bandung, Jawa Barat. Persib saat ini bermain di Liga 1 Indonesia. Julukan mereka adalah Maung Bandung dan Pangeran Biru.', 2.8),	
	('Southampton FC', array['English Premier League', 'FA Cup'], 'Inggris', FALSE, 'Southampton Football Club merupakan sebuah tim sepak bola profesional Inggris yang berbasis di Southampton, (Hampshire), dan bermain di Liga Utama Inggris. Sejak tahun 2001 klub ini memainkan pertandingan kandangnya di (Stadion St Mary''s), sebelumnya mereka memainkan pertandingan kandang di Stadion The Dell.', 3.5),
	('Kashima Antlers', array['J1 League', 'AFC Champions League'], 'Jepang', TRUE, 'Kashima Antlers merupakan sebuah tim sepak bola Jepang yang bermarkas di Kashima, Prefektur Ibaraki, Jepang. Klub ini didirikan pada tahun 1947 oleh Sumitomo Metal Industries, Ltd. di Osaka. Antlers yang berarti tanduk rusa dijadikan nama klub karena secara harafiah nama kota Kashima berarti pulau rusa. Klub ini memainkan pertandingan kandangnya di Stadion Kashima.', 3.5),	
	('Vissel Kobe', array['J1 League', 'AFC Champions League'], 'Jepang', FALSE, 'Vissel Kobe adalah klub sepak bola profesional Jepang yang saat ini bermain di kompetisi Divisi 2 Liga Jepang. Klub ini bermarkas di Kobe, Prefektur Hyogo. Nama Vissel berasal dari penggabungan dua kata dalam bahasa Inggris yakni Victory yang berarti kemenangan dengan Vessel yang berarti kapal.', 3.5),													
	('AC Milan', array['Serie-A','Uefa Europa League', 'Copa Italia'], 'Italia', FALSE, 'Associazione Calcio Milan, sering disebut sebagai A.C. Milan atau hanya Milan, adalah sebuah klub sepak bola Italia yang berbasis di Milan, Lombardia, yang bermain di Serie A. Mereka bermain dengan seragam bergaris merah-hitam dan celana putih (kadang-kadang hitam), sehingga dijuluki rossoneri ("merah-hitam"). Milan adalah tim tersukses kedua dalam sejarah persepak bolaan Italia, menjuarai Serie A 18 kali dan Piala Italia 5 kali.', 3.7),	
	('Inter Milan', array['Serie A', 'Uefa Champions League', 'Copa Italia', 'Supercoppa Italiana'], 'Italia', FALSE, 'Football Club Internazionale Milano, atau yang dikenal dengan nama Internazionale ataupun juga Inter, dan bahasa sehari-hari dikenal sebagai Inter Milan di luar Italia, adalah sebuah klub sepak bola profesional asal Italia yang saat ini bermain di Serie A Liga Italia. Inter Milan mempunyai julukan sebagai il Nerazzurri (si biru hitam), il Biscone (si ular besar), dan juga La Beneamata (yang tersayang). Klub bermain di Serie A (divisi pertama) sejak tahun 1908, dan pendukung Internazionale disebut Interisti.', 4.5),	
	('Juventus FC', array['Serie A', 'Uefa Champions League', 'Copa Italia', 'Supercoppa Italiana'], 'Italia', TRUE, 'Juventus Football Club S.p.A. (BIT: JUVE), biasa disebut sebagai Juventus dan populer dengan nama Juve, adalah klub sepak bola profesional asal Italia yang berbasis di kota Turin, Piemonte. Klub ini didirikan pada tahun 1897 dengan nama Sport Club Juventus oleh sekelompok pelajar muda di kota Turin yang dipimpin oleh Eugenio Canfari dan saudaranya Enrico.', 4.5),	
	('Paris Saint Germain', array['Ligue 1', 'Uefa Champions League', 'Coupe de France'], 'Prancis', TRUE, 'Paris Saint-Germain Football Club atau dikenal luas dengan sebutan PSG merupakan sebuah tim sepak bola Prancis yang bermain di Ligue 1, Prancis. Bermarkas di Paris, Prancis. Klub ini didirikan pada 12 Agustus 1970, berkat penggabungan Paris FC dan dengan Stade Saint-Germain.', 5),
	('FC Bayern Munich', array['Bundesliga','Uefa Champions League', 'DFB Pokal', 'DFB Supercup'], 'Jerman', TRUE, 'Fußball-Club Bayern München e.V., juga dikenal sebagai FC Bayern München, FC Bayern Minga (dalam bahasa Bayern), atau FC Bayern, adalah sebuah klub olahraga Jerman yang berbasis di München, Bayern. Klub ini terkenal sebagai klub paling sukses dalam sejarah sepak bola Jerman, setelah memenangkan rekor 31 gelar nasional dan 20 piala nasional.', 5),	
	('Borussia Dortmund', array['Bundesliga','Uefa Champions League', 'DFB Pokal'], 'Jerman', TRUE, 'Ballspielverein Borussia 09 e.V. Dortmund umumnya dikenal sebagai Borussia Dortmund, atau BVB, adalah klub sepak bola Jerman yang berbasis di Dortmund, Rhine-Westphalia Utara. Didirikan pada tahun 1909 oleh delapan belas pemain sepak bola dari Dortmund, tim sepak bola bagian dari sebuah klub olahraga berbasis keanggotaan besar dengan lebih dari 145.000 anggota, membuat BVB klub olahraga dengan keanggotaan terbesar kedua di Jerman. Dortmund bermain di Bundesliga, tingkat teratas sistem liga sepakbola Jerman.', 4.5),	
	('Manchester United', array['English Premier League','Uefa Champions League', 'FA Cup'], 'Inggris', TRUE, 'Manchester United Football Club adalah sebuah klub sepak bola profesional Inggris yang berbasis di Old Trafford, Manchester Raya, yang bermain di Liga Inggris. ... Pada 1998-1999, klub memenangkan treble dari Liga Premier, Piala FA dan Liga Champions, prestasi belum pernah terjadi sebelumnya untuk klub Inggris.', 4.5),	
	('Manchester City', array['English Premier League', 'Uefa Champions League', 'FA Cup', 'FA Community Shield'], 'Inggris', TRUE, 'Manchester City Football Club (dikenal pula sebagai Man City atau The Citizens) adalah sebuah klub sepak bola profesional dari Inggris yang bermain di Liga Premier Inggris. Klub ini merupakan klub sekota dengan Manchester United dan bermarkas di Stadion Etihad, Manchester.', 5);																				
