version: '3'
services:
    postgres:
        image: postgres:alpine
        ports: 
            - "5432:5432"
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        networks:
            search-net:

networks:
    search-net:
        driver: bridge
        external: true
